# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CPR_Temps.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 777)
        MainWindow.setMaximumSize(QtCore.QSize(958, 777))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/hospital.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("QMainWindow{\n"
                                "background-color: #0055c1;\n"
                                "}\n"
                                "\n"
                                "QPushButton{\n"
                                "     background-color:white ;\n"
                                "    color: rgb(4, 58, 171);\n"
                                "    font-weight: bolder;\n"
                                "}\n"
                                "\n"
                                "QLabel {\n"
                                " color: white;\n"
                                "}\n"
                                "\n"
                                "QListView{\n"
                                " background-color: #4F555C;\n"
                                " color: white;\n"
                                "\n"
                                "}\n"
                                "\n"
                                "QTableView{\n"
                                " background-color: #4F555C;\n"
                                " color: white;\n"
                                "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 330, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 390, 341, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.name_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_label.setFont(font)
        self.name_label.setText("")
        self.name_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_7.addWidget(self.name_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.id_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.id_label.setFont(font)
        self.id_label.setText("")
        self.id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.id_label.setObjectName("id_label")
        self.horizontalLayout_8.addWidget(self.id_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 80, 341, 146))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.date_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.date_label.setFont(font)
        self.date_label.setText("")
        self.date_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_3.addWidget(self.date_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.size_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.size_label.setFont(font)
        self.size_label.setText("")
        self.size_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.size_label.setObjectName("size_label")
        self.horizontalLayout_4.addWidget(self.size_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.length_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.length_label.setFont(font)
        self.length_label.setText("")
        self.length_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.length_label.setObjectName("length_label")
        self.horizontalLayout_5.addWidget(self.length_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.facility_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.facility_label.setFont(font)
        self.facility_label.setText("")
        self.facility_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.facility_label.setObjectName("facility_label")
        self.horizontalLayout_6.addWidget(self.facility_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.layoutWidget.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.layoutWidget.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 491, 651))
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.batch_upload_btn = QtWidgets.QPushButton(self.centralwidget)
        self.batch_upload_btn.setObjectName("batch_upload_btn")
        self.horizontalLayout.addWidget(self.batch_upload_btn)
        self.new_student_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_student_btn.setObjectName("new_student_btn")
        self.horizontalLayout.addWidget(self.new_student_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 3)
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon1)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout.addWidget(self.search_btn, 0, 4, 1, 1)
        self.search_line = QtWidgets.QLineEdit(self.centralwidget)
        self.search_line.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.search_line.setText("")
        self.search_line.setObjectName("search_line")
        self.gridLayout.addWidget(self.search_line, 0, 3, 1, 1)
        self.class_table_label = QtWidgets.QLabel(self.centralwidget)
        self.class_table_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.class_table_label.setAutoFillBackground(False)
        self.class_table_label.setTextFormat(QtCore.Qt.RichText)
        self.class_table_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.class_table_label.setObjectName("class_table_label")
        self.gridLayout.addWidget(self.class_table_label, 0, 2, 1, 1)
        self.class_table_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.class_table_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.class_table_label_2.setAutoFillBackground(False)
        self.class_table_label_2.setTextFormat(QtCore.Qt.RichText)
        self.class_table_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.class_table_label_2.setObjectName("class_table_label_2")
        self.gridLayout.addWidget(self.class_table_label_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.class_tree_widget = QtWidgets.QTreeWidget(self.centralwidget)
        self.class_tree_widget.setObjectName("class_tree_widget")
        self.verticalLayout.addWidget(self.class_tree_widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open_class_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_class_btn.setStyleSheet("")
        self.open_class_btn.setObjectName("open_class_btn")
        self.horizontalLayout_2.addWidget(self.open_class_btn)
        self.create_class_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_class_btn.setObjectName("create_class_btn")
        self.horizontalLayout_2.addWidget(self.create_class_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuUpdate_User = QtWidgets.QMenu(self.menuEdit)
        self.menuUpdate_User.setObjectName("menuUpdate_User")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_2 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_2.setIcon(icon2)
        self.actionNew_2.setObjectName("actionNew_2")
        self.actionOpen_2 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_2.setIcon(icon3)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionChange_User = QtWidgets.QAction(MainWindow)
        self.actionChange_User.setObjectName("actionChange_User")
        self.actionUpdate_User_Info = QtWidgets.QAction(MainWindow)
        self.actionUpdate_User_Info.setObjectName("actionUpdate_User_Info")
        self.close_action = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_action.setIcon(icon4)
        self.close_action.setObjectName("close_action")
        self.menuFile.addAction(self.actionNew_2)
        self.menuFile.addAction(self.actionOpen_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.close_action)
        self.menuUpdate_User.addSeparator()
        self.menuUpdate_User.addAction(self.actionChange_User)
        self.menuUpdate_User.addAction(self.actionUpdate_User_Info)
        self.menuEdit.addAction(self.menuUpdate_User.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.close_action.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.batch_upload_btn, self.new_student_btn)
        MainWindow.setTabOrder(self.new_student_btn, self.search_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPR Template Generator"))
        self.label.setText(_translate("MainWindow", "Class  Information"))
        self.label_3.setText(_translate("MainWindow", "Instructor Information:"))
        self.label_7.setText(_translate("MainWindow", "Name:"))
        self.label_8.setText(_translate("MainWindow", "Trainer ID #:"))
        self.label_2.setText(_translate("MainWindow", "Class Date:"))
        self.label_4.setText(_translate("MainWindow", "Class Size:"))
        self.label_5.setText(_translate("MainWindow", "Class Length:"))
        self.label_6.setText(_translate("MainWindow", "Training Facility:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Class Information"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Site Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address Line 1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Address Line 2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "City"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "State"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Zipcode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Student Table"))
        self.batch_upload_btn.setText(_translate("MainWindow", "Student Batch Upload"))
        self.new_student_btn.setText(_translate("MainWindow", "Add New Student"))
        self.search_line.setPlaceholderText(_translate("MainWindow", "Search"))
        self.class_table_label.setText(_translate("MainWindow", "Class Table"))
        self.class_table_label_2.setText(_translate("MainWindow", "All Classes"))
        self.class_tree_widget.headerItem().setText(0, _translate("MainWindow", "Facility"))
        self.class_tree_widget.headerItem().setText(1, _translate("MainWindow", "Date"))
        self.class_tree_widget.headerItem().setText(2, _translate("MainWindow", "Instructor"))
        self.open_class_btn.setText(_translate("MainWindow", "Open Class"))
        self.create_class_btn.setText(_translate("MainWindow", "Create New Class"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuUpdate_User.setTitle(_translate("MainWindow", "User Options"))
        self.statusbar.setStatusTip(_translate("MainWindow", "CPR Template Generator Tool and Class Manager"))
        self.actionNew_2.setText(_translate("MainWindow", "New"))
        self.actionNew_2.setStatusTip(_translate("MainWindow", "Click to create a new class"))
        self.actionNew_2.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen_2.setText(_translate("MainWindow", "Open"))
        self.actionOpen_2.setStatusTip(_translate("MainWindow", "Click to open a recent file"))
        self.actionOpen_2.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionChange_User.setText(_translate("MainWindow", "Change User"))
        self.actionChange_User.setStatusTip(_translate("MainWindow", "Click to change to a new user"))
        self.actionUpdate_User_Info.setText(_translate("MainWindow", "Update User Info"))
        self.actionUpdate_User_Info.setStatusTip(_translate("MainWindow", "Update user information (i.e. name, ID, etc.)"))
        self.close_action.setText(_translate("MainWindow", "Close"))
        self.close_action.setShortcut(_translate("MainWindow", "Ctrl+W"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

